name: myanimelist_api
version: 0.3.0
description: Asynchronous API wrapper for the official MyAnimeList API v2.
repository: https://github.com/rsktg/MyAnimeList-API

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  json_annotation: ^4.8.1
  http: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.3
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  test: ^1.24.7


